export default {
    REGISTRATION:'التسجيل',
    FIRST_NAME:"اسم الشخصي",
    LAST_NAME:'اسم العائلة',
    DATE_OF_BIRTH:"تاريخ الميلاد",
    MALE:'ذكر',
    FEMALE:'أنثى',
    MOBILE_NUMBER:'رقم الجوال',
    EMAIL:'بريد إلكتروني',
    CATEGORIES:'التصنيف',
    LANGAUGE:'اللغة',
    LOGIN:'دخول',
    SUBMIT:'تأكيد',
    PLEASE_FILL:'المرجو ادخال المعلومات',
    SPECIAL_CHARAC_WARN:'لا تستخدم حرفًا خاصًا',
    PLEASE_SELECT:"المرجو الاختيار",
    MIN_AGE:"الحد الأدنى للعمر  15",
    SAVE_DETAIL:"حفظ التفاصيل",
    OTP_DETAIL:"التحقق من الرمز ",
    RESEND_OTP:" إعادة ارسال الرمز",
    VERIFY:"تحقق",
    REG_SUC:"تم التسجيل بنجاح",
    ABOUT_US:"معلومات عنا",
    DATE:":التاريخ",
    TICKET_ID:"التذكرة:",
    SUBJECT_COMPLAIN:":موضوع الشكوى",
    DES:": التفاصيل",
    VIEW_DETAILS:"عرض التفاصيل",
    STATUS:"الحالة:",
    COMPLAINT:"الشكوى",
    ADD:" + إضافة",
    ADD_COMPLAINT:"إضافة شكوى",
    COMPLAINT_SUB:"موضوع الشكوى",
    SUBMIT:"تأكيد",
    COMPLAINT_DATE:" :تاريخ الشكوى",
    STATUS_DATE:": تاريخ الحالة",
    NO_RESULT_FOUND:"لم يتم العثور على نتيجة",
    NO_SEATS_AVAILABLE:"لا توجد مقاعد متاحة",
    PRICE:"السعر",
    BOOKING:"الحجز",
    DEPARTURE_CITY:"الانطلاق",
    ARRIVAL_CITY:"الوصول",
    AGENCIES:"وكالة",
    BOOK_DATE:":التاريخ",
    NO_OF_PASSENGER:"الركاب",
    MAP:"Map",
    SEARCH_RESULT:"نتيجة البحث",
    HISTORY:"سجلات",
    BOOKING_HISTORY:"سجل الحجوزات",
    POINTS:"النقاط",
    NOTIFICATION:"الإشعارات",
    TRANSACTION_ID:": المعاملة ",
    DEPARTURE_TIME:": وقت الانطلاق ",
    AMOUNT:": الثمن",
    PAYMENT_TYPE:": نوع الدفع",
    FILTER:": اختيارات",
    DATE_FROM:"التاريخ من",
    DATE_TO:"التاريخ إلى",
    PLEASE_SELECT_FIELDS:"المرجو الاختيار", 
    SEARCH:"البحت",
    NO_OF_POINTS:": عدد النقاط",
    TOTAL_POINTS:"عدد النقاط",
    BY_CARD:"بالبطاقة",
    DETAILS_OF_TICKETS:"تفاصيل التذاكر",
    ID:":المعاملة",
    LUXURY:": الانطلاق",
    ARRIVAL_BUS:": الوصول",
    ARRIVAL_TIME:":وقت الوصول",
    APPLY_PROMO_CODE:"تطبيق الرمز الترويجي",
    PAYMENT:"الدفع",
    PAY_BY_CARD:"الدفع بالبطاقة",
    PAY_BY_POINT:"الدفع بالنقاط",
    PROFILE:"الملف الشخصي",
    FIRST_NAME:"اسم الشخصي",
    LAST_NAME:"اسم العائلة",
    CATEGORY:"الفئة",
    EMAIL:"بريد إلكتروني",
    NATIONALITY:"الجنسية",
    JOB:"الوظيفة",
    UPDATE:"تحديث",
    LOG_OUT:"تسجيل الخروج",
    CITY:"المدينة",
    TICKET_INFORMATION:"TICKET INFORMATION",
    TRANSACTION_DATE:": تاريخ المعاملة ",
    TRANSACTION_TIME:": وقت المعاملة ",
    CANCEL:'إلغاء',
    OK:"Ok",
    SUC_BOOK:"تم الحجز بنجاح",
    DEPARTURE:"الانطلاق",
    ARRIVAL:"الوصول",
    TO:"إلى",
    FROM:"من",
    DEPARTURE_DATE:"Departure Date",
    DEPARTURE_CITY_SMALL:"الانطلاق",
    ARRIVAL_CITY_SMAll:"الوصول",
    DEPARTURE_DATE_SMALL:"Departure Date",
    DATE_CAPITAL:"DATE",
    AMOUNT_CAPITAL:"AMOUNT",
    NO_OF_PASSENGER_CAPITAL:"الركاب",
    SAT:"SAT",
    SUN:"SUN",
    MON:"MON",
    TUE:"TUE",
    WED:"WED",
    THU:"THU",
    FRI:"FRI",
    NATIONALITY:'جنسية',
    NOT_FOUND:"غير موجود",
    BOOK_TICKETS:"حجز التذاكر",
    LIST_OF_TICKETS:":قائمة التذاكر",
    aboutText1:"Depuis 1945, la Société des Autocars Transmaghreb <<S A T>> a su prouver par son sérieux que le transport était affaire de professionnels. Elle a réunit au fil des années des collaborateurs consciencieux sachant allier compétence, rapidité et dynamisme afin d’accroître une clientèle satisfaite et fidèle",
    aboutText2:"SAT Transport a fait découvrir aux Marocains une nouvelle manière de voyager. Le réseau de SAT Transport au Maroc  s’est considérablement développé, avec toujours plus de destinations proposées ! Les destinations au départ de chaque ville sont aussi plus nombreuses.",
    aboutText3:"Moins populaire que l’avion et le train sur les longues distances, le bus constitue pourtant un bon moyen pour découvrir le pays. Les gares routières dans les villes proposent des liaisons régulières avec les villes environnantes, et  jusqu’à l’autre bout de Maroc. Les temps de voyage étant significatifs, il est important de prévoir de quoi boire, grignoter, lire et s’occuper. Cela peut parfois aussi être l’occasion de rencontrer d’autres voyageurs.",
    aboutText4:'Voyagez en toute sécurité à bord de nos autocars équipés du confort nécessaire à votre tranquillité. L’ensemble de nos véhicules mis en circulation offrent les services suivants :',
    aboutBullet1:'Sièges confortables inclinables',
    aboutBullet2:'Air conditionné intégrée et éclairage',
    aboutBullet3:'Toilettes',
    aboutBullet4:'Radio',
    aboutBullet5:'Projection vidéo',
    aboutText5:'Nous mettons à votre disposition une Gare routière privée dans laquelle vous pourrez profiter d’un accueil professionnel et chaleureux pour répondre à toutes vos demandes. Nous vous offrons un espace détente ainsi que toutes les commodités pour rendre votre attente plus agréable et vous garantir un voyage dans les meilleures conditions.',
    aboutText6:'En partenariat avec Eurolines, la SAT a su développer un réseau international permettant de répondre à vos besoins en transport vers l’Espagne, l’Italie et la France. La SAT vous fait voyager à travers les grandes villes européennes pour retrouver votre famille, vos amis ou simplement découvrir de nouveaux horizons. A bord, nous vous garantissons des prestations de qualité dans le respect de vos exigences',
    aboutHeading:'Engagement qualité:',
    aboutOrderList1:"Une rapidité d’intervention assurée par une équipe de professionnels rigoureuse et ponctuelle.",
    aboutOrderList2:'Une politique de communication active auprès de nos clients et de nos partenaires.',
    aboutOrderList3:'Un confort et un voyage en toute sécurité sur nos lignes voyageurs.',
    aboutOrderList4:"Le respect des nouvelles législations soumises par les autorités.",
    aboutText7:"Avec plus de 74 ans d’expérience, nous comprenons le rôle vital que nous jouons pour nos clients. Nous nous efforçons de travailler de manière transparente avec nos clients, comme si nous étions un service interne.",
    INVALID_NUMBER:"رقم الجوال غير صالح",
    REG_INVALID_NUMBER:"رقم الجوال غير صحيح أو مستخدم بالفعل",
    INVALID_OTP:"OTP غير صحيح",
    NO_POINTS:"ليس لديك ما يكفي من النقاط",
    ALREADY_APPLY_PR:"تم تطبيق الرمز الترويجي بالفعل",
    ENTERED_PRO:"الرجاء إدخال الرمز الترويجي"
}