export default {
    REGISTRATION:'REGISTRATION',
    FIRST_NAME:"First Name",
    LAST_NAME:'Last Name',
    DATE_OF_BIRTH:"Date of Birth",
    MALE:'Man',
    FEMALE:'Women',
    MOBILE_NUMBER:'Mobile Number',
    EMAIL:'Email',
    CATEGORIES:'Categorie',
    LANGAUGE:'Language',
    LOGIN:'LOGIN',
    SUBMIT:'Submit',
    PLEASE_FILL:'Please Fill',
    SPECIAL_CHARAC_WARN:'do not use special character',
    PLEASE_SELECT:"Please select",
    MIN_AGE:"minimum age require 15",
    SAVE_DETAIL:"Save Details",
    OTP_DETAIL:"VERIFY OTP ",
    RESEND_OTP:"RESEND OTP",
    VERIFY:"VERIFY",
    REG_SUC:"Registered Successfully",
    ABOUT_US:"ABOUT US",
    DATE:"Date:",
    TICKET_ID:"Ticket ID:",
    SUBJECT_COMPLAIN:"Subject Complaint:",
    DES:"Description:",
    VIEW_DETAILS:"VIEW DETAILS",
    STATUS:"Status:",
    COMPLAINT:"COMPLAINT",
    ADD:"ADD +",
    ADD_COMPLAINT:"ADD COMPLAINT",
    COMPLAINT_SUB:"Complaint Subject",
    SUBMIT:"SUBMIT",
    COMPLAINT_DATE:"Complaint Date:",
    STATUS_DATE:"Status Date:",
    NO_RESULT_FOUND:"No Result Found",
    NO_SEATS_AVAILABLE:"No Seats Available",
    PRICE:"Price",
    BOOKING:"BOOKING",
    DEPARTURE_CITY:"Departure",
    ARRIVAL_CITY:"Arrival",
    AGENCIES:"Agencie",
    BOOK_DATE:"Date:",
    NO_OF_PASSENGER:"Passengers",
    MAP:"Map",
    SEARCH_RESULT:"SEARCH RESULT",
    HISTORY:"HISTORY",
    BOOKING_HISTORY:"Booking History",
    POINTS:"Points",
    NOTIFICATION:"Notifications",
    TRANSACTION_ID:"Transaction ID:",
    DEPARTURE_TIME:"Departure Time:",
    AMOUNT:"Amount:",
    PAYMENT_TYPE:"Payment Type:",
    FILTER:"Filter:",
    DATE_FROM:"Date From",
    DATE_TO:"Date To",
    PLEASE_SELECT_FIELDS:"please Select fields",
    SEARCH:"SEARCH",
    NO_OF_POINTS:"No of Points:",
    TOTAL_POINTS:"TOTAL POINTS",
    BY_CARD:"By Card",
    DETAILS_OF_TICKETS:"DETAILS OF TICKETS",
    ID:"Transaction ID:",
    LUXURY:"Departure:",
    ARRIVAL_BUS:"Arrival:",
    ARRIVAL_TIME:"ARRIVAL TIME:",
    APPLY_PROMO_CODE:"APPLY PROMO CODE",
    PAYMENT:"PAYMENT",
    PAY_BY_CARD:"PAY BY CARD",
    PAY_BY_POINT:"PAY BY POINT",
    PROFILE:"PROFILE",
    FIRST_NAME:"First Name",
    LAST_NAME:"Last Name",
    CATEGORY:"Category",
    EMAIL:"Email",
    NATIONALITY:"Nationality",
    JOB:"Job",
    UPDATE:"UPDATE",
    LOG_OUT:"Log Out",
    CITY:"City",
    TICKET_INFORMATION:"TICKET INFORMATION",
    TRANSACTION_DATE:"Transaction Date:",
    TRANSACTION_TIME:"Transaction Time",
    CANCEL:'Cancel',
    OK:"Ok",
    SUC_BOOK:"Successfully Book",
    DEPARTURE:"Departure",
    ARRIVAL:"Arrival",
    TO:"To",
    FROM:"From",
    DEPARTURE_DATE:"Departure Date",
    DEPARTURE_CITY_SMALL:"Departure City",
    ARRIVAL_CITY_SMAll:"Arrival City",
    DEPARTURE_DATE_SMALL:"Departure Date",
    DATE_CAPITAL:"DATE",
    AMOUNT_CAPITAL:"AMOUNT",
    NO_OF_PASSENGER_CAPITAL:"PASSENGERS",
    SAT:"SAT",
    SUN:"SUN",
    MON:"MON",
    TUE:"TUE",
    WED:"WED",
    THU:"THU",
    FRI:"FRI",
    NATIONALITY:'Nationality',
    NOT_FOUND:"NOT FOUND",
    BOOK_TICKETS:"Booked Tickets",
    LIST_OF_TICKETS:"LIST OF TICKETS:",
    aboutText1:"Depuis 1945, la Société des Autocars Transmaghreb <<S A T>> a su prouver par son sérieux que le transport était affaire de professionnels. Elle a réunit au fil des années des collaborateurs consciencieux sachant allier compétence, rapidité et dynamisme afin d’accroître une clientèle satisfaite et fidèle",
    aboutText2:"SAT Transport a fait découvrir aux Marocains une nouvelle manière de voyager. Le réseau de SAT Transport au Maroc  s’est considérablement développé, avec toujours plus de destinations proposées ! Les destinations au départ de chaque ville sont aussi plus nombreuses.",
    aboutText3:"Moins populaire que l’avion et le train sur les longues distances, le bus constitue pourtant un bon moyen pour découvrir le pays. Les gares routières dans les villes proposent des liaisons régulières avec les villes environnantes, et  jusqu’à l’autre bout de Maroc. Les temps de voyage étant significatifs, il est important de prévoir de quoi boire, grignoter, lire et s’occuper. Cela peut parfois aussi être l’occasion de rencontrer d’autres voyageurs.",
    aboutText4:'Voyagez en toute sécurité à bord de nos autocars équipés du confort nécessaire à votre tranquillité. L’ensemble de nos véhicules mis en circulation offrent les services suivants :',
    aboutBullet1:'Sièges confortables inclinables',
    aboutBullet2:'Air conditionné intégrée et éclairage',
    aboutBullet3:'Toilettes',
    aboutBullet4:'Radio',
    aboutBullet5:'Projection vidéo',
    aboutText5:'Nous mettons à votre disposition une Gare routière privée dans laquelle vous pourrez profiter d’un accueil professionnel et chaleureux pour répondre à toutes vos demandes. Nous vous offrons un espace détente ainsi que toutes les commodités pour rendre votre attente plus agréable et vous garantir un voyage dans les meilleures conditions.',
    aboutText6:'En partenariat avec Eurolines, la SAT a su développer un réseau international permettant de répondre à vos besoins en transport vers l’Espagne, l’Italie et la France. La SAT vous fait voyager à travers les grandes villes européennes pour retrouver votre famille, vos amis ou simplement découvrir de nouveaux horizons. A bord, nous vous garantissons des prestations de qualité dans le respect de vos exigences',
    aboutHeading:'Engagement qualité:',
    aboutOrderList1:"Une rapidité d’intervention assurée par une équipe de professionnels rigoureuse et ponctuelle.",
    aboutOrderList2:'Une politique de communication active auprès de nos clients et de nos partenaires.',
    aboutOrderList3:'Un confort et un voyage en toute sécurité sur nos lignes voyageurs.',
    aboutOrderList4:"Le respect des nouvelles législations soumises par les autorités.",
    aboutText7:"Avec plus de 74 ans d’expérience, nous comprenons le rôle vital que nous jouons pour nos clients. Nous nous efforçons de travailler de manière transparente avec nos clients, comme si nous étions un service interne.",
    INVALID_NUMBER:"invalid mobile no",
    REG_INVALID_NUMBER:"Invalid Mobile no or already used",
    INVALID_OTP:"Invalid OTP",
    NO_POINTS:"you dont have enough points",
    ALREADY_APPLY_PR:"you have already apply promo code",
    ENTERED_PRO:"please entered promo code"
}