export default {
    REGISTRATION:'Enregistrement',
    FIRST_NAME:"Nom",
    LAST_NAME:'Prénom',
    DATE_OF_BIRTH:"Date de naissance",
    MALE:'Homme',
    FEMALE:'Femme',
    MOBILE_NUMBER:'N° Portable',
    EMAIL:'Email',
    CATEGORIES:'Categorie',
    LANGAUGE:'Langue',
    LOGIN:'LOGIN',
    SUBMIT:'Valider',
    PLEASE_FILL:'Merci de remplir',
    SPECIAL_CHARAC_WARN:'n\'utilisez pas de caractère spécial',
    PLEASE_SELECT:"Merci de sélectionner",
    MIN_AGE:"minimum age est 15",
    SAVE_DETAIL:"Enregistrer",
    OTP_DETAIL:"VERIFIER OTP ",
    RESEND_OTP:"RE-ENVOYER OTP",
    VERIFY:"Vérifier",
    REG_SUC:"Enregistrement fait avec succès",
    ABOUT_US:"Apropos de nous",
    DATE:"Date:",
    TICKET_ID:"N° Billet:",
    SUBJECT_COMPLAIN:"Sujet :",
    DES:"Description:",
    VIEW_DETAILS:"Détail =>",
    STATUS:"Statut:",
    COMPLAINT:"Réclamation",
    ADD:"Ajouter +",
    ADD_COMPLAINT:"Ajouter Réclamation",
    COMPLAINT_SUB:"Sujet :",
    SUBMIT:"Valider",
    COMPLAINT_DATE:"Date Réclamation:",
    STATUS_DATE:"Date Statut:",
    NO_RESULT_FOUND:"Pas de résultat trouver",
    NO_SEATS_AVAILABLE:"Pas de Place Disponible",
    PRICE:"Prix",
    BOOKING:"BOOKING",
    DEPARTURE_CITY:"Depart",
    ARRIVAL_CITY:"Arrivée",
    AGENCIES:"Agence",
    BOOK_DATE:"Date:",
    NO_OF_PASSENGER:"Passagers",
    MAP:"Map",
    SEARCH_RESULT:"Rechercher",
    HISTORY:"Historique",
    BOOKING_HISTORY:"Historique Booking",
    POINTS:"Points",
    NOTIFICATION:"Notifications",
    TRANSACTION_ID:"Transaction ID:",
    DEPARTURE_TIME:"Heure Depart:",
    AMOUNT:"Tarif:",
    PAYMENT_TYPE:"Type paiement:",
    FILTER:"Filtrer:",
    DATE_FROM:"Date du :",
    DATE_TO:"Date au :",
    PLEASE_SELECT_FIELDS:"Merci de sélectionner des champs",
    SEARCH:"Rechercher",
    NO_OF_POINTS:"Points:",
    TOTAL_POINTS:"TOTAL POINTS",
    BY_CARD:"Par Card",
    DETAILS_OF_TICKETS:"DETAILS DES BILLETS",
    ID:"Transaction ID:",
    LUXURY:"Depart:",
    ARRIVAL_BUS:"Arrivée:",
    ARRIVAL_TIME:"Heure Arrivée:",
    APPLY_PROMO_CODE:"APPLY PROMO CODE",
    PAYMENT:"PAIEMENT",
    PAY_BY_CARD:"PAR CARTE",
    PAY_BY_POINT:"PAR POINT",
    PROFILE:"PROFILE",
    FIRST_NAME:"Nom",
    LAST_NAME:"Prénom",
    CATEGORY:"Categorie",
    EMAIL:"Email",
    NATIONALITY:"Nationalité",
    JOB:"Fonction",
    UPDATE:"UPDATE",
    LOG_OUT:"Déconnecter",
    CITY:"Ville",
    TICKET_INFORMATION:"INFORMATION BILLET ",
    TRANSACTION_DATE:"Transaction Date:",
    TRANSACTION_TIME:"Transaction Heure",
    CANCEL:'Annuler',
    OK:"Ok",
    SUC_BOOK:"Successfully Book",
    DEPARTURE:"Depart",
    ARRIVAL:"Arrivée",
    TO:"Du",
    FROM:"Au",
    DEPARTURE_DATE:"Date Depart",
    DEPARTURE_CITY_SMALL:"Depart",
    ARRIVAL_CITY_SMAll:"Arrivée",
    DEPARTURE_DATE_SMALL:"Date Depart",
    DATE_CAPITAL:"DATE",
    AMOUNT_CAPITAL:"TARIF",
    NO_OF_PASSENGER_CAPITAL:"PASSAGERS",
    SAT:"SAM",
    SUN:"DIM",
    MON:"LUN",
    TUE:"MAR",
    WED:"MER",
    THU:"JEU",
    FRI:"VEN",
    NATIONALITY:"nationalité",
    NOT_FOUND:"NON TROUVE",
    BOOK_TICKETS:"Billets Réservés",
    LIST_OF_TICKETS:"LIST DES BILLETS:",
    aboutText1:"Depuis 1945, la Société des Autocars Transmaghreb <<S A T>> a su prouver par son sérieux que le transport était affaire de professionnels. Elle a réunit au fil des années des collaborateurs consciencieux sachant allier compétence, rapidité et dynamisme afin d’accroître une clientèle satisfaite et fidèle",
    aboutText2:"SAT Transport a fait découvrir aux Marocains une nouvelle manière de voyager. Le réseau de SAT Transport au Maroc  s’est considérablement développé, avec toujours plus de destinations proposées ! Les destinations au départ de chaque ville sont aussi plus nombreuses.",
    aboutText3:"Moins populaire que l’avion et le train sur les longues distances, le bus constitue pourtant un bon moyen pour découvrir le pays. Les gares routières dans les villes proposent des liaisons régulières avec les villes environnantes, et  jusqu’à l’autre bout de Maroc. Les temps de voyage étant significatifs, il est important de prévoir de quoi boire, grignoter, lire et s’occuper. Cela peut parfois aussi être l’occasion de rencontrer d’autres voyageurs.",
    aboutText4:'Voyagez en toute sécurité à bord de nos autocars équipés du confort nécessaire à votre tranquillité. L’ensemble de nos véhicules mis en circulation offrent les services suivants :',
    aboutBullet1:'Sièges confortables inclinables',
    aboutBullet2:'Air conditionné intégrée et éclairage',
    aboutBullet3:'Toilettes',
    aboutBullet4:'Radio',
    aboutBullet5:'Projection vidéo',
    aboutText5:'Nous mettons à votre disposition une Gare routière privée dans laquelle vous pourrez profiter d’un accueil professionnel et chaleureux pour répondre à toutes vos demandes. Nous vous offrons un espace détente ainsi que toutes les commodités pour rendre votre attente plus agréable et vous garantir un voyage dans les meilleures conditions.',
    aboutText6:'En partenariat avec Eurolines, la SAT a su développer un réseau international permettant de répondre à vos besoins en transport vers l’Espagne, l’Italie et la France. La SAT vous fait voyager à travers les grandes villes européennes pour retrouver votre famille, vos amis ou simplement découvrir de nouveaux horizons. A bord, nous vous garantissons des prestations de qualité dans le respect de vos exigences',
    aboutHeading:'Engagement qualité:',
    aboutOrderList1:"Une rapidité d’intervention assurée par une équipe de professionnels rigoureuse et ponctuelle.",
    aboutOrderList2:'Une politique de communication active auprès de nos clients et de nos partenaires.',
    aboutOrderList3:'Un confort et un voyage en toute sécurité sur nos lignes voyageurs.',
    aboutOrderList4:"Le respect des nouvelles législations soumises par les autorités.",
    aboutText7:"Avec plus de 74 ans d’expérience, nous comprenons le rôle vital que nous jouons pour nos clients. Nous nous efforçons de travailler de manière transparente avec nos clients, comme si nous étions un service interne.",
    INVALID_NUMBER:"Numéro de téléphone invalide",
    REG_INVALID_NUMBER:"Mobile non valide non ou déjà utilisé",
    INVALID_OTP:"OTP non valide",
    NO_POINTS:"tu n'as pas assez de points",
    ALREADY_APPLY_PR:"vous avez déjà appliqué le code promotionnel",
    ENTERED_PRO:"veuillez saisir le code promotionnel"
}